services:
  users-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  user-services:
    build: './services/user service'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './services/user service:/app'
    ports:
      - "8001:8000"
    depends_on:
      users-db:
        condition: service_healthy
    env_file:
      - .env

  products-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=products_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - products_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  product-service:
    build: './services/product service'
    command: py manage.py runserver 0.0.0.0:8000
    volumes:
      - './services/product service:/app'
    ports:
      - "8002:8000"
    depends_on:
      products-db:
        condition: service_healthy
    env_file:
      - .env
    

volumes:
  users_data:
  products_data: