services:
  users-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  user-services:
    build: './services/user service'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './services/user service:/app'
    ports:
      - "8001:8000"
    depends_on:
      users-db:
        condition: service_healthy
    env_file:
      - .env

  products-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=products_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - products_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  product-service:
    build: './services/product service'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './services/product service:/app'
    ports:
      - "8002:8000"
    depends_on:
      products-db:
        condition: service_healthy
    env_file:
      - .env
    
  carts-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=carts_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - carts_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  cart-service:
    build: './services/cart service'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './services/cart service:/app'
    ports:
      - "8003:8000"
    depends_on:
      carts-db:
        condition: service_healthy
    env_file:
      - .env
  
  orders-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=orders_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - orders_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  order-service:
    build: './services/order service'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './services/order service:/app'
    ports:
      - "8004:8000"
    depends_on:
      orders-db:
        condition: service_healthy
    env_file:
      - .env

  gateway:
    build: ./services/gateway
    ports:
      - "8080:80"
    depends_on:
      - user-services
      - product-service
      - cart-service
      - order-service

volumes:
  users_data:
  products_data:
  carts_data:
  orders_data: